### ISSUE TITLE
Error In Version v1.6

### ISSUE THREAD

**Issue by Sterile-Gaming** [Devlrxxh/Neptune#14]
```
console@ThunderHosting~ Server marked as starting...
Pulling from pterodactyl/yolks 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
Digest: sha256:c56e86e1de3cf338899d30bcb087f4f2d7708a88c46a6a43de2a931a875df89b 
[ThunderHosting Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -DPaper.IgnoreJavaVersion=true -jar server.jar
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.11+9) Host: Linux 5.15.0-119-generic (amd64)
Loading libraries, please wait...
[14:17:35 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:17:35 INFO]: Reloading ResourceManager: Default, bukkit
[14:17:36 INFO]: Loaded 7 recipes
[14:17:37 INFO]: Starting minecraft server version 1.17.1
[14:17:37 INFO]: Loading properties
[14:17:37 INFO]: This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
[14:17:37 INFO]: Server Ping Player Sample Count: 12
[14:17:37 INFO]: Using 4 threads for Netty based IO
[14:17:38 INFO]: Default game type: SURVIVAL
[14:17:38 INFO]: Generating keypair
[14:17:38 INFO]: Starting Minecraft server on 0.0.0.0:25569
[14:17:38 INFO]: Using epoll channel type
[14:17:38 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[14:17:38 INFO]: Paper: Using Java cipher from Velocity.
[14:17:38 INFO]: [packetevents] Loading packetevents v2.4.0
[14:17:42 INFO]: [Neptune] Loading Neptune v1.6
[14:17:42 INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:17:42 INFO]: Preparing level "world"
[14:17:43 INFO]: Preparing start region for dimension minecraft:overworld
[14:17:43 INFO]: Time elapsed: 325 ms
[14:17:43 INFO]: Preparing start region for dimension minecraft:the_nether
[14:17:44 INFO]: Time elapsed: 686 ms
[14:17:44 INFO]: Preparing start region for dimension minecraft:the_end
[14:17:44 INFO]: Time elapsed: 658 ms
[14:17:44 INFO]: [packetevents] Enabling packetevents v2.4.0
[14:17:44 INFO]: [packetevents] Checking for updates, please wait...
[14:17:44 INFO]: [Neptune] Enabling Neptune v1.6
[14:17:44 ERROR]: Error occurred while enabling Neptune v1.6 (Is it up to date?)
java.lang.RuntimeException: Failed to initialize NMS Reflection
        at dev.lrxh.v1_17_R3.utils.ReflectionUtils.load(ReflectionUtils.java:45) ~[Neptune.jar:?]
        at dev.lrxh.v1_17_R3.utils.ReflectionUtils.<init>(ReflectionUtils.java:21) ~[Neptune.jar:?]
        at dev.lrxh.v1_17_R3.utils.chunk.ChunkUtilsUtil.<init>(ChunkUtilsUtil.java:14) ~[Neptune.jar:?]
        at dev.lrxh.v1_17_R3.v1_17_R3.<init>(v1_17_R3.java:15) ~[Neptune.jar:?]
        at dev.lrxh.versioncontroll.Version.Version.getVersionHandler(Version.java:46) ~[Neptune.jar:?]
        at dev.lrxh.versioncontroll.VersionControll.getVersionHandler(VersionControll.java:21) ~[Neptune.jar:?]
        at dev.lrxh.versioncontroll.VersionControll.<init>(VersionControll.java:15) ~[Neptune.jar:?]
        at dev.lrxh.neptune.Neptune.loadManager(Neptune.java:115) ~[Neptune.jar:?]
        at dev.lrxh.neptune.Neptune.onEnable(Neptune.java:111) ~[Neptune.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoSuchFieldException: k
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at dev.lrxh.v1_17_R3.utils.ReflectionUtils.load(ReflectionUtils.java:34) ~[Neptune.jar:?]
        ... 18 more
[14:17:44 INFO]: [Neptune] Disabling Neptune v1.6
[14:17:45 INFO]: Running delayed init tasks
[14:17:45 INFO]: Done (7.224s)! For help, type "help"
console@ThunderHosting~ Server marked as running...
[14:17:45 INFO]: Timings Reset
[14:17:46 INFO]: [packetevents] You are running the latest release of PacketEvents. Your build: (2.4.0)
```

**Comment by Devlrxxh** [comment]
Will be looked into soon, sorry for the wait
